### ISSUE TITLE
project meetings

### ISSUE THREAD

**Issue by bobbyfunks** [benjaminc2020/BrandNew#1]
I'm available after class M and W.
I have a class at 6 on Tues, but before free.
Off all day Thurs.

**Comment by alnopa9** [comment]
I am available after class on MWF until 6:30.

**Comment by ebeshero** [comment]
All— Just note that DH instructor Team meetings are scheduled from 4:15 until 5:30ish on Fridays!

**Comment by bryant-bolyen** [comment]
Just recently sent this schedule to an interviewer.

Availability:
Mondays
- 12 - 2 pm
- 3 - 5 pm

Tuesdays
- Before 10 am
- 11:30 am - 2 pm
- 4 - 5 pm

Wednesdays
- 1 - 2 pm


Thursdays
- Before 10 am 
- 1 - 2 pm
- 4 - 5 pm

Fridays
- 12 - 2 pm
- 3 - 5 pm

**Comment by benjaminc2020** [comment]
We have successfully created our Repo and cloned it to our computers. We've invited all the collaborators. The README file is created and we've started organizing our repo.

For meeting times, I am available after class M, W, F until 5:30, and then available again at 7PM.

**Comment by ebeshero** [comment]
@benjaminc2020 Hi Ben! Just showing you how to ping people! @Bryant-LettucePrime @bobbyfunks

**Comment by ebeshero** [comment]
- [ ] Let's do X task. Assigned to @Bryant-LettucePrime 
- [x] Let's do X task. Assigned to @Bryant-LettucePrime 
- [x] Let's do X task. Assigned to @Bryant-LettucePrime 
- [ ] Let's do X task. Assigned to @Bryant-LettucePrime 
- [ ] Let's do X task. Assigned to @Bryant-LettucePrime

**Comment by bobbyfunks** [comment]
@ebeshero cool thanks

**Comment by alnopa9** [comment]
Closing this issue, but the agreed upon weekly project meetings after this week will be Mondays after class in the Center for Digital Text!
