### ISSUE TITLE
Project Checkpoint Three

### ISSUE THREAD

**Issue by alnopa9** [benjaminc2020/BrandNew#4]
- [x] Some team members work on developing page(s) for the project website, creating navigation menu (using a SSI), and working with section, div, and span elements. Try using CSS flex to control your horizontal layout. Work out a file directory structure for the GitHub repo to separate project website files from XML markup.
- [x] Others concentrate on completing markup, up-converting files to project XML with regex (as needed), and refining the project schema.

Great job with progressing on this project, everyone! 😸 
The website, although pretty empty, is shaping up nicely! I know you don't have much to put on it at the moment, but the navigation bar looks very sharp! I also like that the links go to the corresponding pages and aren't just broken links! The hover effect on the text is a nice touch as well. Ben, great job with the SSI! 👍 
Bryant and Bobby, you guys are pumping out markup! 🥇 

Looking forward to the project meeting on Wednesday!

@bobbyfunks @benjaminc2020 @Bryant-LettucePrime

**Comment by ebeshero** [comment]
Excellent work so far, team!
